version: "3.9"
services:
  db:
    image: postgres
    env_file:
      - .env
    expose:
      - $DB_PORT
    volumes:
      - /var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
  web:
    build: .
    env_file:
      - .env
    tty: true
    ports:
      - "$WEB_PORT:$WEB_PORT"
    volumes:
      - ./:/app
    depends_on:
      - db
    links:
      - db
#BCRYPT CAUSING ERR BC OF OP SYS
