version: "3.9"
services:
  db:
    image: postgres
    env_file:
      - .env
    expose:
      - $DB_PORT
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
  web:
    build: .
    env_file:
      - .env
    tty: true
    ports:
      - "3000:$WEB_PORT"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    links:
      - db
#BCRYPT CAUSING ERR BC OF OP SYS
